### PR TITLE
they

### PR DESCRIPTION
**Pull request by LordDamionDevil**

### CODE REVIEW

**Comment by AnEverydayZomby** [comment]
lol

**Comment by DigitalJokerMan** [comment]
the*

**Comment by LordDamionDevil** [comment]
> the*

fuck you

**Comment by DigitalJokerMan** [comment]
> > the*
> 
> fuck you

please do :weary:

**Comment by AnEverydayZomby** [comment]
> > > the*
> > 
> > 
> > fuck you
> 
> please do 😩

quote

**Comment by DigitalJokerMan** [comment]
> > > > the*
> > > 
> > > 
> > > fuck you
> > 
> > 
> > please do 😩
> 
> quote

undertale rule 34

**Pull request merged**
